const docs=document.getElementById('docs'),forms=document.getElementById('forms'),cat=document.getElementById('cat'),typeFilter=document.getElementById('typeFilter'),find=document.getElementById('find'),globalSearch=document.getElementById('global');
function card(x){return `<article class="card"><div class="meta"><span class="tag">${x.category}</span><span class="filetype">${x.type}</span></div><h3>${x.name}</h3><p>${x.description}</p><a class="link" href="${x.file}" download>📥 Tải xuống</a></article>`}
function render(q=''){q=q.toLowerCase().trim();const a=documents.filter(x=>(!cat.value||x.category===cat.value)&&(!typeFilter.value||x.type===typeFilter.value)&&(!q||(x.name+' '+x.description+' '+x.category+' '+x.type).toLowerCase().includes(q)));docs.innerHTML=a.map(card).join('')||'<article class="card"><h3>Không tìm thấy</h3><p>Hãy thử từ khóa khác.</p></article>';document.getElementById('totalCount').innerHTML=String(documents.length).padStart(2,'0')+' <small>tài liệu</small>'}
function renderForms(){forms.innerHTML=documents.filter(x=>x.type==='Biểu mẫu').map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span><strong>${x.name}</strong><small>${x.category} • ${x.description}</small></span><a href="${x.file}" download>📥 Tải Word</a></div>`).join('')}
function quick(q){globalSearch.value=q;find.value=q;cat.value='';typeFilter.value='';render(q);document.getElementById('van-ban').scrollIntoView()}
function goSearch(){quick(globalSearch.value)}
cat.onchange=()=>render(find.value);typeFilter.onchange=()=>render(find.value);find.oninput=()=>render(find.value);render();renderForms();
function calculate(){const s=document.getElementById('calc').value.replace(/,/g,'').replace(/\s/g,'');const o=document.getElementById('calcout');if(!/^[0-9+\-*/().]+$/.test(s)){o.textContent='Biểu thức không hợp lệ';return}try{o.textContent=new Intl.NumberFormat('vi-VN').format(Function('return('+s+')')())+' đồng'}catch{o.textContent='Biểu thức không hợp lệ'}}
const one=['','một','hai','ba','bốn','năm','sáu','bảy','tám','chín'];function r3(n){let h=Math.floor(n/100),t=Math.floor(n/10)%10,u=n%10,s=h?one[h]+' trăm':'';if(t)s+=(s?' ':'')+(t===1?'mười':one[t]+' mươi')+(u===1&&t>1?' mốt':u===5&&t?' lăm':u?' '+one[u]:'');else if(u)s+=(h?' linh ':' ')+one[u];return s.trim()}function money(){let raw=document.getElementById('money').value.replace(/\D/g,''),n=Number(raw),o=document.getElementById('moneyout');if(!raw||!Number.isSafeInteger(n)){o.textContent='Hãy nhập số tiền hợp lệ';return}if(n===0){o.textContent='Không đồng';return}let u=['','nghìn','triệu','tỷ'],p=[],i=0;while(n){let x=n%1000;if(x)p.unshift(r3(x)+(u[i]?' '+u[i]:''));n=Math.floor(n/1000);i++}o.textContent=p.join(' ')+' đồng'}
document.getElementById('today').textContent=new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');